name: Deploy to server

on: push

jobs:
    first_jobs:
        name: First Jobs
        runs-on: ubuntu-latest

        env:
            NAME: Código Facilito

        steps:
            - name: Working Directory
              run: ls -la
            - name: Action
              uses: actions/checkout@v4
            - name: Working Directory after action
              run: ls -la
    second_jobs:
        if: ${{ github.ref == 'refs/heads/main' }}
        needs: first_jobs
        runs-on: ubuntu-latest

        steps:
            - name: Hola Mundo
              run: echo "Hola Mundo segundo"
